server:
  servlet:
    context-path: /produdoro/api

spring:
  data:
    mongodb:
      uri: mongodb+srv://Allan:jgln2PHZvN3lXAYN@cluster.o0nj2ph.mongodb.net/wakanda?retryWrites=true&w=majority&tls=true

springdoc:
  swagger-ui:
    path: /swagger