server:
  servlet:
    context-path: /produdoro/api

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb+srv://allanbrenogomesdias:tyo91rOblsy6dTxy@cluster0.klvdq.mongodb.net/Cluster0?retryWrites=true&w=majority&appName=Cluster0 # URL do MongoDB
      auto-index-creation: true

logging:
  level:
    root: INFO # Nível de log padrão
    org.springframework.data.mongodb: DEBUG # Nível de log específico para MongoDB